// Defines the complete weapon catalog, including display metadata, rarity, and
// the per-level stat curves consumed by the game systems.

export type WeaponId =
  | "pulse"
  | "flak"
  | "ricochet"
  | "boomerang"
  | "stinger"
  | "frag"
  | "siege"
  | "orbital"
  | "laser"
  | "missile"
  | "frost"
  | "drone"
  | "flame"
  | "emp"
  | "gravity"
  | "lightning"
  | "nova"
  | "harpoon"
  | "anchor"
  | "lattice"
  | "rebound"
  | "vortex"
  | "beam"
  | "chrono"
  | "prism";

export interface WeaponLevel {
  damage: number;
  cooldown: number;
  projectiles: number;
  speed: number;
  range: number;
  pierce: number;
  aoe: number;
  special: number;
}

export interface WeaponDef {
  id: WeaponId;
  name: string;
  description: string;
  icon: string;
  color: string;
  maxLevel: number;
  levels: WeaponLevel[];
  rarity: "common" | "uncommon" | "rare" | "legendary";
}

const WEAPONS: Record<WeaponId, WeaponDef> = {
  pulse: {
    id: "pulse",
    name: "Fission Pulse",
    description: "Splits into chained projectiles on hit.",
    icon: "⚛",
    color: "#b4ff00",
    maxLevel: 5,
    rarity: "rare",
    // Reuses the aoe field to represent the maximum split depth for chained shots.
    levels: [
      {
        damage: 9.1,
        cooldown: 48,
        projectiles: 1,
        speed: 9,
        range: 650,
        pierce: 1,
        aoe: 1,
        special: 0,
      },
      {
        damage: 17.46,
        cooldown: 44,
        projectiles: 2,
        speed: 9,
        range: 690,
        pierce: 1,
        aoe: 1,
        special: 0,
      },
      {
        damage: 24.71,
        cooldown: 40,
        projectiles: 3,
        speed: 10,
        range: 730,
        pierce: 1,
        aoe: 2,
        special: 0,
      },
      {
        damage: 31.58,
        cooldown: 36,
        projectiles: 4,
        speed: 11,
        range: 780,
        pierce: 1,
        aoe: 2,
        special: 0,
      },
      {
        damage: 38.22,
        cooldown: 32,
        projectiles: 5,
        speed: 12,
        range: 840,
        pierce: 2,
        aoe: 3,
        special: 0,
      },
    ],
  },
  flak: {
    id: "flak",
    name: "Flak Cannon",
    description: "Short-range burst. Devastating up close.",
    icon: "K",
    color: "#ffcc00",
    maxLevel: 5,
    rarity: "common",
    levels: [
      {
        damage: 2.52,
        cooldown: 30,
        projectiles: 5,
        speed: 7,
        range: 220,
        pierce: 1,
        aoe: 0,
        special: 30,
      },
      {
        damage: 3.97,
        cooldown: 27,
        projectiles: 7,
        speed: 7,
        range: 240,
        pierce: 1,
        aoe: 0,
        special: 35,
      },
      {
        damage: 5.22,
        cooldown: 24,
        projectiles: 9,
        speed: 8,
        range: 260,
        pierce: 1,
        aoe: 0,
        special: 40,
      },
      {
        damage: 6.41,
        cooldown: 20,
        projectiles: 11,
        speed: 8,
        range: 290,
        pierce: 2,
        aoe: 0,
        special: 45,
      },
      {
        damage: 7.56,
        cooldown: 16,
        projectiles: 14,
        speed: 9,
        range: 310,
        pierce: 2,
        aoe: 0,
        special: 50,
      },
    ],
  },
  ricochet: {
    id: "ricochet",
    name: "Ricochet Disc",
    description: "Bounces between enemies on hit.",
    icon: "R",
    color: "#b8c6db",
    maxLevel: 5,
    rarity: "common",
    levels: [
      {
        damage: 9.8,
        cooldown: 46,
        projectiles: 1,
        speed: 6,
        range: 600,
        pierce: 1,
        aoe: 0,
        special: 2,
      },
      {
        damage: 19.65,
        cooldown: 42,
        projectiles: 2,
        speed: 6.5,
        range: 640,
        pierce: 1,
        aoe: 0,
        special: 3,
      },
      {
        damage: 28.18,
        cooldown: 38,
        projectiles: 3,
        speed: 7,
        range: 670,
        pierce: 1,
        aoe: 0,
        special: 4,
      },
      {
        damage: 36.28,
        cooldown: 34,
        projectiles: 4,
        speed: 7.5,
        range: 720,
        pierce: 1,
        aoe: 0,
        special: 5,
      },
      {
        damage: 44.1,
        cooldown: 30,
        projectiles: 5,
        speed: 8,
        range: 780,
        pierce: 1,
        aoe: 0,
        special: 7,
      },
    ],
  },
  boomerang: {
    id: "boomerang",
    name: "Boomerang Blade",
    description: "Returns to player after reaching max range.",
    icon: "B",
    color: "#39ff7f",
    maxLevel: 5,
    rarity: "common",
    levels: [
      {
        damage: 14,
        cooldown: 44,
        projectiles: 1,
        speed: 5,
        range: 260,
        pierce: 3,
        aoe: 0,
        special: 0,
      },
      {
        damage: 30.89,
        cooldown: 38,
        projectiles: 2,
        speed: 5.5,
        range: 290,
        pierce: 4,
        aoe: 0,
        special: 0,
      },
      {
        damage: 45.51,
        cooldown: 32,
        projectiles: 3,
        speed: 6,
        range: 320,
        pierce: 5,
        aoe: 0,
        special: 0,
      },
      {
        damage: 59.39,
        cooldown: 26,
        projectiles: 4,
        speed: 6.5,
        range: 350,
        pierce: 7,
        aoe: 0,
        special: 0,
      },
      {
        damage: 72.8,
        cooldown: 20,
        projectiles: 5,
        speed: 7,
        range: 390,
        pierce: 10,
        aoe: 0,
        special: 0,
      },
    ],
  },
  stinger: {
    id: "stinger",
    name: "Stinger Array",
    description: "Fires high-velocity micro-bolts in a tight burst.",
    icon: "!",
    color: "#00e5ff",
    maxLevel: 5,
    rarity: "common",
    levels: [
      {
        damage: 12.6,
        cooldown: 24,
        projectiles: 1,
        speed: 14,
        range: 700,
        pierce: 1,
        aoe: 0,
        special: 0,
      },
      {
        damage: 20.92,
        cooldown: 20,
        projectiles: 2,
        speed: 15,
        range: 760,
        pierce: 1,
        aoe: 0,
        special: 0,
      },
      {
        damage: 28.13,
        cooldown: 16,
        projectiles: 3,
        speed: 16,
        range: 820,
        pierce: 1,
        aoe: 0,
        special: 0,
      },
      {
        damage: 34.97,
        cooldown: 13,
        projectiles: 4,
        speed: 17,
        range: 880,
        pierce: 2,
        aoe: 0,
        special: 0,
      },
      {
        damage: 41.58,
        cooldown: 10,
        projectiles: 5,
        speed: 18,
        range: 940,
        pierce: 2,
        aoe: 0,
        special: 0,
      },
    ],
  },
  frag: {
    id: "frag",
    name: "Frag Shell",
    description: "Wide spread shell with explosive splash on impact.",
    icon: "#",
    color: "#ff6b2c",
    maxLevel: 5,
    rarity: "common",
    levels: [
      {
        damage: 7,
        cooldown: 34,
        projectiles: 3,
        speed: 7,
        range: 480,
        pierce: 1,
        aoe: 40,
        special: 50,
      },
      {
        damage: 11.22,
        cooldown: 30,
        projectiles: 4,
        speed: 7.5,
        range: 510,
        pierce: 1,
        aoe: 50,
        special: 55,
      },
      {
        damage: 14.88,
        cooldown: 26,
        projectiles: 5,
        speed: 8,
        range: 540,
        pierce: 1,
        aoe: 60,
        special: 60,
      },
      {
        damage: 18.35,
        cooldown: 22,
        projectiles: 6,
        speed: 8.5,
        range: 580,
        pierce: 1,
        aoe: 75,
        special: 65,
      },
      {
        damage: 21.7,
        cooldown: 18,
        projectiles: 7,
        speed: 9,
        range: 620,
        pierce: 2,
        aoe: 90,
        special: 70,
      },
    ],
  },
  siege: {
    id: "siege",
    name: "Impact Warhead",
    description:
      "Heavy shell that detonates on first contact, unleashing a circular shockwave.",
    icon: "@",
    color: "#4fc3f7",
    maxLevel: 5,
    rarity: "common",
    levels: [
      {
        damage: 18.2,
        cooldown: 60,
        projectiles: 1,
        speed: 6,
        range: 640,
        pierce: 1,
        aoe: 60,
        special: 0,
      },
      {
        damage: 43.29,
        cooldown: 52,
        projectiles: 2,
        speed: 6.5,
        range: 680,
        pierce: 1,
        aoe: 75,
        special: 0,
      },
      {
        damage: 65.02,
        cooldown: 44,
        projectiles: 3,
        speed: 7,
        range: 720,
        pierce: 1,
        aoe: 90,
        special: 0,
      },
      {
        damage: 85.63,
        cooldown: 37,
        projectiles: 4,
        speed: 7.5,
        range: 780,
        pierce: 1,
        aoe: 110,
        special: 0,
      },
      {
        damage: 105.56,
        cooldown: 30,
        projectiles: 5,
        speed: 8,
        range: 840,
        pierce: 1,
        aoe: 130,
        special: 0,
      },
    ],
  },
  orbital: {
    id: "orbital",
    name: "Orbital Shield",
    description: "Rotating orbs that damage on contact.",
    icon: "O",
    color: "#b44aff",
    maxLevel: 5,
    rarity: "uncommon",
    levels: [
      {
        damage: 4.2,
        cooldown: 0,
        projectiles: 2,
        speed: 2,
        range: 50,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
      {
        damage: 6.61,
        cooldown: 0,
        projectiles: 3,
        speed: 2.2,
        range: 58,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
      {
        damage: 8.7,
        cooldown: 0,
        projectiles: 4,
        speed: 2.5,
        range: 66,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
      {
        damage: 10.68,
        cooldown: 0,
        projectiles: 5,
        speed: 2.8,
        range: 74,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
      {
        damage: 12.6,
        cooldown: 0,
        projectiles: 6,
        speed: 3,
        range: 82,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
    ],
  },
  laser: {
    id: "laser",
    name: "Laser Beam",
    description: "Piercing beam that locks onto enemies.",
    icon: "L",
    color: "#ff3a8c",
    maxLevel: 5,
    rarity: "uncommon",
    levels: [
      {
        damage: 3.5,
        cooldown: 22,
        projectiles: 1,
        speed: 0,
        range: 480,
        pierce: 3,
        aoe: 0,
        special: 10,
      },
      {
        damage: 5.51,
        cooldown: 20,
        projectiles: 2,
        speed: 0,
        range: 540,
        pierce: 4,
        aoe: 0,
        special: 12,
      },
      {
        damage: 7.25,
        cooldown: 18,
        projectiles: 3,
        speed: 0,
        range: 600,
        pierce: 6,
        aoe: 0,
        special: 14,
      },
      {
        damage: 8.9,
        cooldown: 16,
        projectiles: 4,
        speed: 0,
        range: 680,
        pierce: 8,
        aoe: 0,
        special: 16,
      },
      {
        damage: 10.5,
        cooldown: 14,
        projectiles: 5,
        speed: 0,
        range: 780,
        pierce: 10,
        aoe: 0,
        special: 18,
      },
    ],
  },
  missile: {
    id: "missile",
    name: "Homing Missiles",
    description: "Lock-on tracking with splash damage.",
    icon: "M",
    color: "#39ff7f",
    maxLevel: 5,
    rarity: "uncommon",
    levels: [
      {
        damage: 10.5,
        cooldown: 42,
        projectiles: 1,
        speed: 4,
        range: 780,
        pierce: 1,
        aoe: 30,
        special: 0.03,
      },
      {
        damage: 18.34,
        cooldown: 38,
        projectiles: 2,
        speed: 4.5,
        range: 840,
        pierce: 1,
        aoe: 35,
        special: 0.04,
      },
      {
        damage: 25.13,
        cooldown: 34,
        projectiles: 3,
        speed: 5,
        range: 910,
        pierce: 1,
        aoe: 42,
        special: 0.05,
      },
      {
        damage: 31.57,
        cooldown: 30,
        projectiles: 4,
        speed: 5.5,
        range: 980,
        pierce: 1,
        aoe: 50,
        special: 0.06,
      },
      {
        damage: 37.8,
        cooldown: 26,
        projectiles: 5,
        speed: 6,
        range: 1080,
        pierce: 1,
        aoe: 60,
        special: 0.07,
      },
    ],
  },
  frost: {
    id: "frost",
    name: "Cryo Beam",
    description: "Beam that slows and damages enemies.",
    icon: "I",
    color: "#88eeff",
    maxLevel: 5,
    rarity: "uncommon",
    levels: [
      {
        damage: 2.8,
        cooldown: 25,
        projectiles: 1,
        speed: 0,
        range: 420,
        pierce: 3,
        aoe: 0,
        special: 10,
      },
      {
        damage: 4.41,
        cooldown: 22,
        projectiles: 1,
        speed: 0,
        range: 460,
        pierce: 4,
        aoe: 0,
        special: 12,
      },
      {
        damage: 5.8,
        cooldown: 20,
        projectiles: 2,
        speed: 0,
        range: 500,
        pierce: 5,
        aoe: 0,
        special: 14,
      },
      {
        damage: 7.12,
        cooldown: 18,
        projectiles: 2,
        speed: 0,
        range: 550,
        pierce: 7,
        aoe: 0,
        special: 16,
      },
      {
        damage: 8.4,
        cooldown: 15,
        projectiles: 3,
        speed: 0,
        range: 600,
        pierce: 10,
        aoe: 0,
        special: 18,
      },
    ],
  },
  drone: {
    id: "drone",
    name: "Attack Drones",
    description: "Autonomous drones that orbit and attack.",
    icon: "U",
    color: "#00bcd4",
    maxLevel: 5,
    rarity: "uncommon",
    levels: [
      {
        damage: 3.5,
        cooldown: 0,
        projectiles: 2,
        speed: 2.5,
        range: 128,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
      {
        damage: 5.51,
        cooldown: 0,
        projectiles: 3,
        speed: 2.7,
        range: 142,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
      {
        damage: 7.25,
        cooldown: 0,
        projectiles: 4,
        speed: 3,
        range: 156,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
      {
        damage: 8.9,
        cooldown: 0,
        projectiles: 5,
        speed: 3.2,
        range: 170,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
      {
        damage: 10.5,
        cooldown: 0,
        projectiles: 6,
        speed: 3.5,
        range: 184,
        pierce: 99,
        aoe: 0,
        special: 0,
      },
    ],
  },
  flame: {
    id: "flame",
    name: "Flamethrower",
    description: "Short-range continuous cone of fire.",
    icon: "W",
    color: "#ff5722",
    maxLevel: 5,
    rarity: "uncommon",
    levels: [
      {
        damage: 1.19,
        cooldown: 4,
        projectiles: 3,
        speed: 4,
        range: 180,
        pierce: 2,
        aoe: 0,
        special: 15,
      },
      {
        damage: 1.87,
        cooldown: 4,
        projectiles: 4,
        speed: 4.5,
        range: 200,
        pierce: 2,
        aoe: 0,
        special: 18,
      },
      {
        damage: 2.47,
        cooldown: 4,
        projectiles: 5,
        speed: 5,
        range: 230,
        pierce: 3,
        aoe: 0,
        special: 22,
      },
      {
        damage: 3.03,
        cooldown: 4,
        projectiles: 6,
        speed: 5.5,
        range: 250,
        pierce: 3,
        aoe: 0,
        special: 25,
      },
      {
        damage: 3.57,
        cooldown: 4,
        projectiles: 8,
        speed: 6,
        range: 280,
        pierce: 4,
        aoe: 0,
        special: 30,
      },
    ],
  },
  emp: {
    id: "emp",
    name: "EMP Burst",
    description: "AoE pulse that stuns enemies briefly.",
    icon: "E",
    color: "#00e5ff",
    maxLevel: 5,
    rarity: "rare",
    levels: [
      {
        damage: 7,
        cooldown: 120,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 100,
        special: 30,
      },
      {
        damage: 11.82,
        cooldown: 110,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 120,
        special: 40,
      },
      {
        damage: 16,
        cooldown: 100,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 140,
        special: 50,
      },
      {
        damage: 19.97,
        cooldown: 90,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 170,
        special: 60,
      },
      {
        damage: 23.8,
        cooldown: 80,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 200,
        special: 75,
      },
    ],
  },
  gravity: {
    id: "gravity",
    name: "Gravity Well",
    description: "Launches a singularity that attracts enemies.",
    icon: "G",
    color: "#b44aff",
    maxLevel: 5,
    rarity: "rare",
    levels: [
      {
        damage: 1.4,
        cooldown: 480,
        projectiles: 1,
        speed: 4,
        range: 280,
        pierce: 99,
        aoe: 90,
        special: 200,
      },
      {
        damage: 3.01,
        cooldown: 460,
        projectiles: 1,
        speed: 4.2,
        range: 300,
        pierce: 99,
        aoe: 115,
        special: 210,
      },
      {
        damage: 4.4,
        cooldown: 440,
        projectiles: 1,
        speed: 4.4,
        range: 320,
        pierce: 99,
        aoe: 140,
        special: 220,
      },
      {
        damage: 5.72,
        cooldown: 420,
        projectiles: 1,
        speed: 4.6,
        range: 350,
        pierce: 99,
        aoe: 170,
        special: 230,
      },
      {
        damage: 7,
        cooldown: 400,
        projectiles: 1,
        speed: 4.8,
        range: 380,
        pierce: 99,
        aoe: 200,
        special: 240,
      },
    ],
  },
  lightning: {
    id: "lightning",
    name: "Chain Lightning",
    description: "Arcs between nearby enemies.",
    icon: "Z",
    color: "#00e5ff",
    maxLevel: 5,
    rarity: "rare",
    levels: [
      {
        damage: 4.48,
        cooldown: 40,
        projectiles: 1,
        speed: 0,
        range: 320,
        pierce: 1,
        aoe: 0,
        special: 2,
      },
      {
        damage: 7.31,
        cooldown: 38,
        projectiles: 1,
        speed: 0,
        range: 360,
        pierce: 1,
        aoe: 0,
        special: 3,
      },
      {
        damage: 9.76,
        cooldown: 35,
        projectiles: 1,
        speed: 0,
        range: 400,
        pierce: 1,
        aoe: 0,
        special: 4,
      },
      {
        damage: 12.09,
        cooldown: 32,
        projectiles: 2,
        speed: 0,
        range: 430,
        pierce: 1,
        aoe: 0,
        special: 5,
      },
      {
        damage: 14.34,
        cooldown: 28,
        projectiles: 2,
        speed: 0,
        range: 480,
        pierce: 1,
        aoe: 0,
        special: 7,
      },
    ],
  },
  nova: {
    id: "nova",
    name: "Nova Pulse",
    description: "Expanding ring of fire damage.",
    icon: "N",
    color: "#ff8c00",
    maxLevel: 5,
    rarity: "rare",
    levels: [
      {
        damage: 10.5,
        cooldown: 100,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 150,
        special: 20,
      },
      {
        damage: 17.44,
        cooldown: 90,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 180,
        special: 22,
      },
      {
        damage: 23.44,
        cooldown: 80,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 210,
        special: 24,
      },
      {
        damage: 29.14,
        cooldown: 70,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 250,
        special: 26,
      },
      {
        damage: 34.65,
        cooldown: 60,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 300,
        special: 30,
      },
    ],
  },
  harpoon: {
    id: "harpoon",
    name: "Void Harpoon",
    description:
      "Launches out inert, then returns to drag and damage enemies along the tether path.",
    icon: "V",
    color: "#6ee7ff",
    maxLevel: 5,
    rarity: "rare",
    levels: [
      {
        damage: 8,
        cooldown: 70,
        projectiles: 1,
        speed: 11,
        range: 392,
        pierce: 1,
        aoe: 0,
        special: 42,
      },
      {
        damage: 14.12,
        cooldown: 64,
        projectiles: 2,
        speed: 11.5,
        range: 420,
        pierce: 1,
        aoe: 0,
        special: 46,
      },
      {
        damage: 19.41,
        cooldown: 58,
        projectiles: 3,
        speed: 12,
        range: 448,
        pierce: 1,
        aoe: 0,
        special: 50,
      },
      {
        damage: 24.43,
        cooldown: 52,
        projectiles: 4,
        speed: 12.5,
        range: 476,
        pierce: 1,
        aoe: 0,
        special: 54,
      },
      {
        damage: 29.28,
        cooldown: 46,
        projectiles: 5,
        speed: 13,
        range: 504,
        pierce: 1,
        aoe: 0,
        special: 58,
      },
    ],
  },
  anchor: {
    id: "anchor",
    name: "Temporal Anchor",
    description:
      "Rewinds marked enemies, seals them in temporal shells, then detonates delayed echo bursts.",
    icon: "T",
    color: "#7cb7ff",
    maxLevel: 5,
    rarity: "legendary",
    levels: [
      {
        damage: 4.2,
        cooldown: 190,
        projectiles: 1,
        speed: 7,
        range: 520,
        pierce: 99,
        aoe: 120,
        special: 58,
      },
      {
        damage: 7.2,
        cooldown: 176,
        projectiles: 1,
        speed: 7.4,
        range: 560,
        pierce: 99,
        aoe: 135,
        special: 64,
      },
      {
        damage: 9.8,
        cooldown: 162,
        projectiles: 1,
        speed: 7.8,
        range: 600,
        pierce: 99,
        aoe: 150,
        special: 70,
      },
      {
        damage: 12.3,
        cooldown: 148,
        projectiles: 1,
        speed: 8.2,
        range: 650,
        pierce: 99,
        aoe: 170,
        special: 78,
      },
      {
        damage: 14.6,
        cooldown: 134,
        projectiles: 1,
        speed: 8.6,
        range: 700,
        pierce: 99,
        aoe: 195,
        special: 86,
      },
    ],
  },
  lattice: {
    id: "lattice",
    name: "Thunder Lattice",
    description: "Deploys electric nodes and arcs between the linked grid.",
    icon: "N",
    color: "#7efff5",
    maxLevel: 5,
    rarity: "rare",
    levels: [
      {
        damage: 2.6,
        cooldown: 84,
        projectiles: 3,
        speed: 0,
        range: 170,
        pierce: 99,
        aoe: 100,
        special: 960,
      },
      {
        damage: 4.59,
        cooldown: 78,
        projectiles: 4,
        speed: 0,
        range: 190,
        pierce: 99,
        aoe: 112,
        special: 990,
      },
      {
        damage: 6.32,
        cooldown: 72,
        projectiles: 5,
        speed: 0,
        range: 210,
        pierce: 99,
        aoe: 124,
        special: 1020,
      },
      {
        damage: 7.95,
        cooldown: 66,
        projectiles: 6,
        speed: 0,
        range: 235,
        pierce: 99,
        aoe: 138,
        special: 1050,
      },
      {
        damage: 9.52,
        cooldown: 60,
        projectiles: 7,
        speed: 0,
        range: 260,
        pierce: 99,
        aoe: 154,
        special: 1080,
      },
    ],
  },
  rebound: {
    id: "rebound",
    name: "Pursuit Halo",
    description: "Launches a forward halo that deals sustained area damage.",
    icon: "R",
    color: "#ffde8c",
    maxLevel: 5,
    rarity: "common",
    levels: [
      {
        damage: 7.8,
        cooldown: 84,
        projectiles: 1,
        speed: 11.5,
        range: 700,
        pierce: 1,
        aoe: 52,
        special: 117,
      },
      {
        damage: 12.57,
        cooldown: 76,
        projectiles: 1,
        speed: 12,
        range: 760,
        pierce: 1,
        aoe: 60,
        special: 134,
      },
      {
        damage: 16.69,
        cooldown: 68,
        projectiles: 1,
        speed: 12.5,
        range: 820,
        pierce: 1,
        aoe: 69,
        special: 153,
      },
      {
        damage: 20.61,
        cooldown: 60,
        projectiles: 1,
        speed: 13,
        range: 880,
        pierce: 1,
        aoe: 78,
        special: 173,
      },
      {
        damage: 24.39,
        cooldown: 52,
        projectiles: 1,
        speed: 13.5,
        range: 940,
        pierce: 1,
        aoe: 88,
        special: 195,
      },
    ],
  },
  vortex: {
    id: "vortex",
    name: "Plasma Vortex",
    description: "Spinning damage field around the ship.",
    icon: "Y",
    color: "#e040fb",
    maxLevel: 5,
    rarity: "rare",
    levels: [
      {
        damage: 2.8,
        cooldown: 120,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 100,
        special: 120,
      },
      {
        damage: 4.49,
        cooldown: 108,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 120,
        special: 140,
      },
      {
        damage: 5.95,
        cooldown: 96,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 140,
        special: 160,
      },
      {
        damage: 7.34,
        cooldown: 84,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 165,
        special: 180,
      },
      {
        damage: 8.68,
        cooldown: 72,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 190,
        special: 200,
      },
    ],
  },
  beam: {
    id: "beam",
    name: "Beam Cannon",
    description: "Charges a devastating heavy beam.",
    icon: "F",
    color: "#fafafa",
    maxLevel: 5,
    rarity: "rare",
    levels: [
      {
        damage: 35,
        cooldown: 120,
        projectiles: 1,
        speed: 0,
        range: 960,
        pierce: 99,
        aoe: 0,
        special: 12,
      },
      {
        damage: 61.13,
        cooldown: 110,
        projectiles: 1,
        speed: 0,
        range: 1020,
        pierce: 99,
        aoe: 0,
        special: 14,
      },
      {
        damage: 83.77,
        cooldown: 100,
        projectiles: 1,
        speed: 0,
        range: 1080,
        pierce: 99,
        aoe: 0,
        special: 16,
      },
      {
        damage: 105.24,
        cooldown: 90,
        projectiles: 1,
        speed: 0,
        range: 1150,
        pierce: 99,
        aoe: 20,
        special: 18,
      },
      {
        damage: 126,
        cooldown: 80,
        projectiles: 1,
        speed: 0,
        range: 1260,
        pierce: 99,
        aoe: 30,
        special: 20,
      },
    ],
  },
  chrono: {
    id: "chrono",
    name: "Chrono Field",
    description: "Slows time for all enemies in the area.",
    icon: "\u0398",
    color: "#448aff",
    maxLevel: 5,
    rarity: "legendary",
    levels: [
      {
        damage: 1.4,
        cooldown: 180,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 130,
        special: 180,
      },
      {
        damage: 2.2,
        cooldown: 165,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 155,
        special: 210,
      },
      {
        damage: 2.9,
        cooldown: 150,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 180,
        special: 240,
      },
      {
        damage: 3.56,
        cooldown: 135,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 210,
        special: 270,
      },
      {
        damage: 4.2,
        cooldown: 120,
        projectiles: 1,
        speed: 0,
        range: 0,
        pierce: 99,
        aoe: 240,
        special: 300,
      },
    ],
  },
  prism: {
    id: "prism",
    name: "Prism Array",
    description:
      "Persistent lock beam that refracts into rainbow branch lasers.",
    icon: "\u03A8",
    color: "#ff6bef",
    maxLevel: 5,
    rarity: "legendary",
    levels: [
      {
        damage: 1,
        cooldown: 60,
        projectiles: 1,
        speed: 0,
        range: 480,
        pierce: 3,
        aoe: 0,
        special: 3,
      },
      {
        damage: 1.6,
        cooldown: 54,
        projectiles: 1,
        speed: 0,
        range: 530,
        pierce: 4,
        aoe: 0,
        special: 4,
      },
      {
        damage: 2.13,
        cooldown: 48,
        projectiles: 1,
        speed: 0,
        range: 580,
        pierce: 5,
        aoe: 0,
        special: 5,
      },
      {
        damage: 2.62,
        cooldown: 42,
        projectiles: 2,
        speed: 0,
        range: 640,
        pierce: 6,
        aoe: 0,
        special: 6,
      },
      {
        damage: 3.1,
        cooldown: 36,
        projectiles: 2,
        speed: 0,
        range: 700,
        pierce: 8,
        aoe: 0,
        special: 7,
      },
    ],
  },
};

export function getWeapon(id: WeaponId): WeaponDef {
  return WEAPONS[id];
}

export function getWeaponLevel(id: WeaponId, level: number): WeaponLevel {
  const w = WEAPONS[id];
  return w.levels[Math.min(level, w.maxLevel) - 1];
}

export function getAllWeapons(): WeaponDef[] {
  return Object.values(WEAPONS);
}

export const WEAPON_IDS: WeaponId[] = Object.keys(WEAPONS) as WeaponId[];
