export type StationType =
  | "tracking"
  | "data_reception"
  | "command"
  | "multi_purpose";

export type StationStatus = "operational" | "maintenance" | "offline";

export interface GroundStation {
  id: string;
  name: string;
  operator: string;
  lat: number;
  lng: number;
  country: string;
  type: StationType;
  supportedSatellites: string[];
  antennaCount: number;
  bandSupport: string[];
  throughputGbps: number;
  status: StationStatus;
  sdgContribution: number[];
  elevationMaskDeg: number;
}

export interface DataPipeline {
  satellite: string;
  groundStation: string;
  processingCenter: string;
  sdgIndicators: string[];
  latencyMinutes: number;
}

export const OPERATOR_COLORS: Record<string, string> = {
  ESA: "#00e5ff",
  NASA: "#ff6b2c",
  ISRO: "#ffd54f",
  JAXA: "#ff3a5c",
  CNSA: "#b44aff",
  KARI: "#39ff7f",
  ROSCOSMOS: "#ff9e64",
  DLR: "#00e5ff",
  CNES: "#4aa8ff",
  Other: "#8a9bbd",
};

export const STATION_TYPE_LABELS: Record<StationType, string> = {
  tracking: "Tracking",
  data_reception: "Data Reception",
  command: "Command & Control",
  multi_purpose: "Multi-Purpose",
};

export const STATION_TYPE_SHAPES: Record<StationType, string> = {
  tracking: "circle",
  data_reception: "diamond",
  command: "square",
  multi_purpose: "star",
};

export const MOCK_GROUND_STATIONS: GroundStation[] = [
  // Lists ESA-operated ground stations used by the mock network dataset.
  {
    id: "gs-001",
    name: "ESTRACK Kiruna",
    operator: "ESA",
    lat: 67.86,
    lng: 20.96,
    country: "Sweden",
    type: "multi_purpose",
    supportedSatellites: [
      "Sentinel-1",
      "Sentinel-2",
      "Sentinel-3",
      "CryoSat-2",
    ],
    antennaCount: 4,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 4.8,
    status: "operational",
    sdgContribution: [13, 14, 15, 6],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-002",
    name: "ESTRACK Maspalomas",
    operator: "ESA",
    lat: 27.76,
    lng: -15.63,
    country: "Spain",
    type: "data_reception",
    supportedSatellites: ["Sentinel-2", "Sentinel-3", "Aeolus"],
    antennaCount: 3,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 3.2,
    status: "operational",
    sdgContribution: [13, 14, 15],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-003",
    name: "ESTRACK Redu",
    operator: "ESA",
    lat: 50.0,
    lng: 5.15,
    country: "Belgium",
    type: "command",
    supportedSatellites: ["Galileo", "EGNOS", "Sentinel-1"],
    antennaCount: 6,
    bandSupport: ["S-band", "Ka-band"],
    throughputGbps: 2.5,
    status: "operational",
    sdgContribution: [9, 11, 13],
    elevationMaskDeg: 7,
  },
  {
    id: "gs-004",
    name: "ESTRACK Kourou",
    operator: "ESA",
    lat: 5.24,
    lng: -52.77,
    country: "French Guiana",
    type: "tracking",
    supportedSatellites: ["Ariane-6 Upper Stage", "Sentinel-1"],
    antennaCount: 2,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 1.8,
    status: "operational",
    sdgContribution: [9, 13],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-005",
    name: "ESTRACK New Norcia",
    operator: "ESA",
    lat: -31.05,
    lng: 116.19,
    country: "Australia",
    type: "multi_purpose",
    supportedSatellites: ["Mars Express", "ExoMars", "JUICE"],
    antennaCount: 2,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 5.2,
    status: "operational",
    sdgContribution: [9, 13, 17],
    elevationMaskDeg: 5,
  },
  // Lists NASA-operated ground stations used by the mock network dataset.
  {
    id: "gs-006",
    name: "DSN Goldstone",
    operator: "NASA",
    lat: 35.43,
    lng: -116.89,
    country: "USA",
    type: "multi_purpose",
    supportedSatellites: [
      "Voyager-1",
      "Voyager-2",
      "JWST",
      "MODIS/Aqua",
      "MODIS/Terra",
    ],
    antennaCount: 5,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 8.4,
    status: "operational",
    sdgContribution: [9, 13, 14, 15],
    elevationMaskDeg: 6,
  },
  {
    id: "gs-007",
    name: "DSN Madrid",
    operator: "NASA",
    lat: 40.43,
    lng: -4.25,
    country: "Spain",
    type: "multi_purpose",
    supportedSatellites: ["JWST", "Mars Reconnaissance Orbiter", "GRACE-FO"],
    antennaCount: 4,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 7.6,
    status: "operational",
    sdgContribution: [9, 13, 6],
    elevationMaskDeg: 6,
  },
  {
    id: "gs-008",
    name: "DSN Canberra",
    operator: "NASA",
    lat: -35.4,
    lng: 148.98,
    country: "Australia",
    type: "multi_purpose",
    supportedSatellites: ["Voyager-2", "Perseverance", "ICESat-2"],
    antennaCount: 4,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 7.2,
    status: "operational",
    sdgContribution: [9, 13, 15],
    elevationMaskDeg: 6,
  },
  {
    id: "gs-009",
    name: "Wallops Flight Facility",
    operator: "NASA",
    lat: 37.94,
    lng: -75.47,
    country: "USA",
    type: "data_reception",
    supportedSatellites: ["Landsat-9", "SMAP", "VIIRS/Suomi NPP"],
    antennaCount: 3,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 4.2,
    status: "operational",
    sdgContribution: [2, 6, 13, 15],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-010",
    name: "White Sands Complex",
    operator: "NASA",
    lat: 32.54,
    lng: -106.61,
    country: "USA",
    type: "tracking",
    supportedSatellites: ["TDRS", "ISS", "Hubble"],
    antennaCount: 3,
    bandSupport: ["S-band", "Ka-band"],
    throughputGbps: 6.0,
    status: "maintenance",
    sdgContribution: [9, 3],
    elevationMaskDeg: 5,
  },
  // Lists ISRO-operated ground stations used by the mock network dataset.
  {
    id: "gs-011",
    name: "ISTRAC Bengaluru",
    operator: "ISRO",
    lat: 12.97,
    lng: 77.59,
    country: "India",
    type: "multi_purpose",
    supportedSatellites: ["Chandrayaan-3", "Aditya-L1", "INSAT-3DS"],
    antennaCount: 5,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 3.8,
    status: "operational",
    sdgContribution: [9, 13, 2, 6],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-012",
    name: "ISTRAC Port Blair",
    operator: "ISRO",
    lat: 11.67,
    lng: 92.73,
    country: "India",
    type: "data_reception",
    supportedSatellites: ["INSAT-3DS", "Oceansat-3"],
    antennaCount: 2,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 2.1,
    status: "operational",
    sdgContribution: [14, 13],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-013",
    name: "ISTRAC Mauritius",
    operator: "ISRO",
    lat: -20.35,
    lng: 57.5,
    country: "Mauritius",
    type: "tracking",
    supportedSatellites: ["GSAT-30", "Chandrayaan-3"],
    antennaCount: 1,
    bandSupport: ["S-band"],
    throughputGbps: 1.2,
    status: "operational",
    sdgContribution: [9],
    elevationMaskDeg: 8,
  },
  // Lists JAXA-operated ground stations used by the mock network dataset.
  {
    id: "gs-014",
    name: "JAXA Tsukuba Space Center",
    operator: "JAXA",
    lat: 36.07,
    lng: 140.13,
    country: "Japan",
    type: "multi_purpose",
    supportedSatellites: ["ALOS-4", "GOSAT-GW", "Himawari-9"],
    antennaCount: 6,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 5.5,
    status: "operational",
    sdgContribution: [9, 13, 15, 11],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-015",
    name: "JAXA Usuda Deep Space",
    operator: "JAXA",
    lat: 36.13,
    lng: 138.36,
    country: "Japan",
    type: "tracking",
    supportedSatellites: ["Hayabusa-2", "MMX"],
    antennaCount: 1,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 2.0,
    status: "operational",
    sdgContribution: [9],
    elevationMaskDeg: 10,
  },
  {
    id: "gs-016",
    name: "JAXA Okinawa",
    operator: "JAXA",
    lat: 26.33,
    lng: 127.77,
    country: "Japan",
    type: "data_reception",
    supportedSatellites: ["ALOS-4", "GCOM-W"],
    antennaCount: 2,
    bandSupport: ["X-band"],
    throughputGbps: 3.0,
    status: "operational",
    sdgContribution: [13, 14],
    elevationMaskDeg: 5,
  },
  // Lists CNSA-operated ground stations used by the mock network dataset.
  {
    id: "gs-017",
    name: "Beijing Aerospace Control Center",
    operator: "CNSA",
    lat: 39.91,
    lng: 116.39,
    country: "China",
    type: "command",
    supportedSatellites: ["Tiangong", "Tianwen-1", "Chang'e-6"],
    antennaCount: 8,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 6.5,
    status: "operational",
    sdgContribution: [9],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-018",
    name: "Kashgar Deep Space Station",
    operator: "CNSA",
    lat: 39.47,
    lng: 75.98,
    country: "China",
    type: "multi_purpose",
    supportedSatellites: ["Tianwen-1", "Chang'e-6"],
    antennaCount: 3,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 4.0,
    status: "operational",
    sdgContribution: [9],
    elevationMaskDeg: 8,
  },
  {
    id: "gs-019",
    name: "Jiamusi Station",
    operator: "CNSA",
    lat: 46.8,
    lng: 130.36,
    country: "China",
    type: "data_reception",
    supportedSatellites: ["Gaofen-7", "HJ-2A", "FY-4B"],
    antennaCount: 4,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 3.6,
    status: "maintenance",
    sdgContribution: [13, 15, 11],
    elevationMaskDeg: 5,
  },
  // Lists additional international ground stations that broaden the mock network coverage.
  {
    id: "gs-020",
    name: "KARI Daejeon",
    operator: "KARI",
    lat: 36.37,
    lng: 127.36,
    country: "South Korea",
    type: "multi_purpose",
    supportedSatellites: ["KOMPSAT-7", "Danuri"],
    antennaCount: 3,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 2.8,
    status: "operational",
    sdgContribution: [9, 13],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-021",
    name: "Svalbard Satellite Station",
    operator: "KSAT",
    lat: 78.23,
    lng: 15.39,
    country: "Norway",
    type: "data_reception",
    supportedSatellites: [
      "Sentinel-1",
      "Sentinel-2",
      "Sentinel-3",
      "MODIS/Aqua",
      "Landsat-9",
    ],
    antennaCount: 31,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 12.5,
    status: "operational",
    sdgContribution: [13, 14, 15, 6, 2],
    elevationMaskDeg: 3,
  },
  {
    id: "gs-022",
    name: "CNES Toulouse Center",
    operator: "CNES",
    lat: 43.56,
    lng: 1.48,
    country: "France",
    type: "command",
    supportedSatellites: ["SPOT-7", "Pleiades Neo", "SWOT"],
    antennaCount: 3,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 3.5,
    status: "operational",
    sdgContribution: [6, 13, 14],
    elevationMaskDeg: 7,
  },
  {
    id: "gs-023",
    name: "DLR Weilheim",
    operator: "DLR",
    lat: 47.88,
    lng: 11.08,
    country: "Germany",
    type: "multi_purpose",
    supportedSatellites: ["TerraSAR-X", "TanDEM-X", "EnMAP"],
    antennaCount: 4,
    bandSupport: ["S-band", "X-band", "Ka-band"],
    throughputGbps: 4.5,
    status: "operational",
    sdgContribution: [9, 13, 15, 11],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-024",
    name: "Hartebeesthoek RAO",
    operator: "SANSA",
    lat: -25.89,
    lng: 27.69,
    country: "South Africa",
    type: "data_reception",
    supportedSatellites: ["Sentinel-2", "Landsat-9", "CBERS-4A"],
    antennaCount: 3,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 2.4,
    status: "operational",
    sdgContribution: [2, 6, 13, 15],
    elevationMaskDeg: 5,
  },
  {
    id: "gs-025",
    name: "McMurdo Ground Station",
    operator: "NASA",
    lat: -77.85,
    lng: 166.67,
    country: "Antarctica",
    type: "data_reception",
    supportedSatellites: ["ICESat-2", "CryoSat-2", "GRACE-FO"],
    antennaCount: 2,
    bandSupport: ["S-band", "X-band"],
    throughputGbps: 1.5,
    status: "offline",
    sdgContribution: [13, 14],
    elevationMaskDeg: 5,
  },
];

export const MOCK_DATA_PIPELINES: DataPipeline[] = [
  {
    satellite: "Sentinel-1",
    groundStation: "ESTRACK Kiruna",
    processingCenter: "ESA Copernicus Hub",
    sdgIndicators: ["SDG 13: Climate Action", "SDG 15: Life on Land"],
    latencyMinutes: 45,
  },
  {
    satellite: "Sentinel-2",
    groundStation: "Svalbard Satellite Station",
    processingCenter: "ESA Copernicus Hub",
    sdgIndicators: ["SDG 15: Life on Land", "SDG 2: Zero Hunger"],
    latencyMinutes: 30,
  },
  {
    satellite: "MODIS/Aqua",
    groundStation: "DSN Goldstone",
    processingCenter: "NASA EOSDIS",
    sdgIndicators: ["SDG 13: Climate Action", "SDG 14: Life Below Water"],
    latencyMinutes: 60,
  },
  {
    satellite: "Landsat-9",
    groundStation: "Wallops Flight Facility",
    processingCenter: "USGS EROS Center",
    sdgIndicators: ["SDG 15: Life on Land", "SDG 6: Clean Water"],
    latencyMinutes: 120,
  },
  {
    satellite: "GRACE-FO",
    groundStation: "DSN Madrid",
    processingCenter: "NASA JPL",
    sdgIndicators: ["SDG 6: Clean Water", "SDG 13: Climate Action"],
    latencyMinutes: 90,
  },
  {
    satellite: "CryoSat-2",
    groundStation: "ESTRACK Kiruna",
    processingCenter: "ESA CryoSat IPF",
    sdgIndicators: ["SDG 13: Climate Action", "SDG 14: Life Below Water"],
    latencyMinutes: 55,
  },
  {
    satellite: "ICESat-2",
    groundStation: "McMurdo Ground Station",
    processingCenter: "NASA NSIDC",
    sdgIndicators: ["SDG 13: Climate Action", "SDG 14: Life Below Water"],
    latencyMinutes: 180,
  },
  {
    satellite: "SMAP",
    groundStation: "Wallops Flight Facility",
    processingCenter: "NASA NSIDC",
    sdgIndicators: ["SDG 2: Zero Hunger", "SDG 6: Clean Water"],
    latencyMinutes: 75,
  },
  {
    satellite: "ALOS-4",
    groundStation: "JAXA Tsukuba Space Center",
    processingCenter: "JAXA EORC",
    sdgIndicators: ["SDG 15: Life on Land", "SDG 11: Sustainable Cities"],
    latencyMinutes: 40,
  },
  {
    satellite: "Gaofen-7",
    groundStation: "Jiamusi Station",
    processingCenter: "CNSA RADI",
    sdgIndicators: ["SDG 11: Sustainable Cities", "SDG 15: Life on Land"],
    latencyMinutes: 50,
  },
  {
    satellite: "INSAT-3DS",
    groundStation: "ISTRAC Bengaluru",
    processingCenter: "ISRO MOSDAC",
    sdgIndicators: ["SDG 13: Climate Action", "SDG 2: Zero Hunger"],
    latencyMinutes: 15,
  },
  {
    satellite: "Sentinel-3",
    groundStation: "ESTRACK Maspalomas",
    processingCenter: "EUMETSAT",
    sdgIndicators: ["SDG 14: Life Below Water", "SDG 13: Climate Action"],
    latencyMinutes: 35,
  },
  {
    satellite: "SWOT",
    groundStation: "CNES Toulouse Center",
    processingCenter: "CNES AVISO",
    sdgIndicators: ["SDG 6: Clean Water", "SDG 14: Life Below Water"],
    latencyMinutes: 65,
  },
  {
    satellite: "TerraSAR-X",
    groundStation: "DLR Weilheim",
    processingCenter: "DLR EOC",
    sdgIndicators: ["SDG 11: Sustainable Cities", "SDG 13: Climate Action"],
    latencyMinutes: 25,
  },
  {
    satellite: "KOMPSAT-7",
    groundStation: "KARI Daejeon",
    processingCenter: "KARI NISS",
    sdgIndicators: ["SDG 9: Industry & Innovation", "SDG 13: Climate Action"],
    latencyMinutes: 35,
  },
];
